apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: "my_ip"
  labels:
    app: wordpress-deployment
spec:
  type: LoadBalancer
  selector:
    app: wordpress-deployment
  ports:
  - name: wordpress
    port: 5050
    targetPort: 5050
    nodePort: 5050
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress-deployment
spec:
  selector:
    matchLabels:
      app: wordpress-deployment
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress-deployment
    spec:
      containers:
      - name: wordpress
        image: wordpress
        imagePullPolicy: Never
        env:
        - name: DB_HOST
          value: http://minikube_ip
        - name: WORDPRESS_HOST
          value: http://minikube_ip:5050/
        ports:
        - containerPort: 5050
