apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: "my_ip"
  labels:
    app: wordpress-deployment
spec:
  type: LoadBalancer
  selector:
    app: wordpress-deployment
  ports:
  - name: wordpress
    port: 5050
    targetPort: 5050
    nodePort: 5050
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pv-claim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress-deployment
spec:
  selector:
    matchLabels:
      app: wordpress-deployment
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress-deployment
    spec:
      containers:
      - name: wordpress
        image: wordpress
        imagePullPolicy: Never
        env:
        - name: DB_HOST
          value: http://minikube_ip
        - name: WORDPRESS_HOST
          value: http://minikube_ip:5050/
        ports:
        - containerPort: 5050
        # livenessProbe:
        #   httpGet:
        #     host: 192.168.49.128
        #     path: /
        #     port: 5050
        #     scheme: HTTP
        #   initialDelaySeconds: 60
        #   periodSeconds: 20
        #   timeoutSeconds: 10
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /www/wordpress
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wordpress-pv-claim
