apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  labels:
    app: ftps
spec:
  type: LoadBalancer
  ports:
  - port : 80
    protocol: TCP
  selector:
    app: ftps 
  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: grafana
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ftps 
  template:
    metadata:
      labels:
        app: ftps 
    spec:
      containers:
      - name: ftps
        image: micahvdk/ftpserver
        ports:
        - containerPort: 21
